title: Zixuan Xia
name: Zixuan Xia
position: Master Student
email: xxiazixuan824@gmail.com

description: >-
  I am a second-year Master’s student in Computer Science at the [University of Bern](https://www.unibe.ch/). I received my Bachelor’s degree in Software Engineering from [Xi’an Jiaotong University](https://en.xjtu.edu.cn/) in China.

  My research interests lie in optimization algorithms in deep learning, generative models, and computer vision.

baseurl: "" # for GitHub Pages
url: "https://sumxiaa.github.io"

twitter_username: Sumxiaa
github_username: Sumxiaa
google_scholar: jvJz7XQAAAAJ&hl
last_updated: August 8, 2025

# ✅ 使用官方推荐方式设置主题
remote_theme: jekyll/minima

plugins:
  - jekyll-feed

sass:
  style: compact


