# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Zixuan Xia
name: Zixuan Xia
position: Master Student
email: xxiazixuan824@gmail.com
description: >-
I am a second-year Master’s student in Computer Science at the [University of Bern](https://www.unibe.ch/). I received my Bachelor’s degree in Software Engineering from Xi’an Jiaotong University[https://en.xjtu.edu.cn/] in China.

My research interests lie in optimization algorithms in deep learning, generative models, and computer vision.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://Sumxiaa.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: Sumxiaa
github_username: Sumxiaa
google_scholar: jvJz7XQAAAAJ&hl
last_updated: August 8, 2025

# Build settings
theme: minima
plugins:
  - jekyll-feed

sass:
  style: compact

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
